version: "3"

services:
  chall:
    build: src
    expose:
      - "8080"
    tty: true
    environment:
      CTF_CIDRS: 192.168.0.0/16,127.0.0.0/8
    volumes:
      - ./src/flag.txt:/flag.txt
      - ./src/assets:/assets

  nginx:
    image: nginx:1.17
    restart: always
    volumes:
      - ./src/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 42004:80
    depends_on:
      - chall
